#define _CRT_SECURE_NO_WARNINGS
#include "LOG.HPP"
#include "../CONFIG.HPP"
#include "DOS.HPP"

#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#ifdef __WATCOMC__
#include <i86.h>
#endif
#ifdef __DJGPP__
#include <dos.h>
#endif

#if defined(__DJGPP__) || defined(__WATCOMC__)
void log_setBiosCursor(int x, int y) {
    union REGS r;
    memset(&r,0,sizeof(r));
    r.w.ax = 0x200;
    r.h.bh = 0;
    r.h.dl = (unsigned char)(x&255);
    r.h.dh = (unsigned char)(y&255);
    int386(0x10, &r, &r);
}
#else
void log_setBiosCursor(int x, int y) { UNUSED(x); UNUSED(y); }
#endif

static char temp_buffer1[4096]; // not thread safe (done this way due to WatcomC)
static char temp_buffer2[4096]; // not thread safe (done this way due to WatcomC)

#define TOBUFFER(__buffer__) va_list ap;\
    va_start(ap, fmt);\
    vsprintf(__buffer__, fmt, ap);\
    va_end(ap);

#define GETLOGID ("["+currentTimeString()+"]").c_str()
void logIt(const char *str, bool printIt) {
  if (printIt) {
    log_setBiosCursor(0,0);
    printf(str);
  }
  FILE *out = fopen(logFileName,"a");
  if (out != NULL) {
    fprintf(out,"%s %s",GETLOGID,str);
    fclose(out);
  }
}

void initLogging() {

  FILE *out = fopen(logFileName,"wb"); // create new
  if (out != NULL) fclose(out);

  logIt("\n",false);
  logIt(">>>Started new log\n",false);
  logIt("---------------------------\n",false);
}

void log(const char *fmt, ...) {
  TOBUFFER(temp_buffer1);
  sprintf(temp_buffer2,"%s\n",temp_buffer1);
  logIt(temp_buffer2,true);
}

void logp(const char *fmt, ...) {
  TOBUFFER(temp_buffer1);
  sprintf(temp_buffer2,"%s\n",temp_buffer1);
  logIt(temp_buffer2,true);
}

void logi(const char *fmt, ...) {
  TOBUFFER(temp_buffer1);
  sprintf(temp_buffer2,"INFO: %s\n",temp_buffer1);
  logIt(temp_buffer2,true);
}

void logd(const char *fmt, ...) {
  TOBUFFER(temp_buffer1);
  sprintf(temp_buffer2,"DEBUG: %s\n",temp_buffer1);
  logIt(temp_buffer2,false);
}

void loge(const char *fmt, ...) {
  TOBUFFER(temp_buffer1);
  sprintf(temp_buffer2,"ERROR: %s\n",temp_buffer1);
  logIt(temp_buffer2,true);
}

